// Generated by CoffeeScript 1.3.3
(function() {

  (function(jQuery) {
    return $.fn.extend({
      timestack: function(options) {
        var defaults;
        defaults = {
          click: function(content) {
            return console.log(content);
          },
          width: '100%',
          parse: function(str) {
            return moment(str);
          },
          format: function(start, end) {
            return "" + (start.format('MMM YYYY')) + " - " + (end.format('MMM YYYY'));
          },
          color: '#eee'
        };
        options = $.extend(defaults, options);
        return this.each(function() {
          var $li, $obj, $ul, content, diff, earliest, i, items, labelspan, latest, offset, timespan, titlespan, width, _i, _len, _results;
          $obj = $(this);
          $ul = $obj.children('ul');
          $ul.css('width', options.width).addClass('timestack-events');
          earliest = null;
          latest = null;
          items = $ul.children('li').map(function() {
            var $li, obj;
            $li = $(this);
            obj = {
              start: options.parse($li.attr('data-start')),
              end: options.parse($li.attr('data-end')),
              title: $li.attr('data-title'),
              color: $li.attr('data-color') || options.color,
              li: $li
            };
            if (!(earliest && earliest < obj.start)) {
              earliest = obj.start;
            }
            if (!(latest && latest > obj.end)) {
              latest = obj.end;
            }
            return obj;
          });
          diff = latest - earliest;
          _results = [];
          for (_i = 0, _len = items.length; _i < _len; _i++) {
            i = items[_i];
            $li = i.li;
            timespan = $("<em>(" + (options.format(i.start, i.end)) + ")</em>").addClass('timestack-time');
            titlespan = $("<span>" + i.title + " </span>").addClass("timestack-title");
            labelspan = $("<span></span>").addClass('timestack-label').append(titlespan).append(timespan);
            content = $li.children().wrapAll("<div class='timestack-content'></div>").parent().hide();
            width = ((i.end - i.start) / diff * 100).toFixed(2);
            offset = ((i.start - earliest) / diff * 100).toFixed(2);
            _results.push($li.prepend(labelspan).css("margin-left", "" + offset + "%").css("width", "" + width + "%").css('background-color', i.color).click((function(content) {
              return function() {
                return options.click(content.children());
              };
            })(content)));
          }
          return _results;
        });
      }
    });
  })(jQuery);

}).call(this);
